### ISSUE TITLE
Configure reverse proxy and ssl certificate

### ISSUE THREAD

**Issue by acka47** [metafacture/metafacture-blog#7] opened 2021-09-10 10:17 UTC
URL: https://blog.metafacture.org

- [x] change urls in gatsby-config
- [x] remove pathPrefix
- [x] configure reverse proxy
- [x] add ssl certificate

**Comment by katauber** [comment] 2021-09-30 12:06
Added PR https://github.com/metafacture/metafacture-blog/pull/9 in which the url is changed in the gatsby-config to blog.metafacture.org and the path prefix is removed. After merging this will be published at https://metafacture.github.io/metafacture-blog/, so @dr0i can configure the reverse proxy.

**Comment by dr0i** [comment] 2021-10-04 07:11
Closed incidentially by #9, reopening.

**Comment by dr0i** [comment] 2021-10-04 07:50
Configured reverse proxy as in blog.skohub.io. Please check @katauber if things are working as expected.

**Comment by katauber** [comment] 2021-10-04 08:02
The icons of github and twitter are a little bit bigger than they should 😄 I try to find out why.
![image](https://user-images.githubusercontent.com/72247962/135814956-6e464778-7c5b-4d68-9a31-72e15aef7e24.png)

**Comment by katauber** [comment] 2021-10-04 08:21
There seems to be something wrong with the pathes of the links. If I click on a blockpost the url is e.g. https://blog.metafacture.org/new-beginnings/ but I stay on the main page. Maybe the reason of this problem is the same reason for the big icons?
In the skohub blog the icons are also very big on the github-io page but have the right size on blog.skohub.io, so maybe the problem is in the configuration of the reverse proxy @dr0i ?

**Comment by dr0i** [comment] 2021-10-04 08:40
Thx @katauber. Indeed I forgot an `$1` doing a `RewriteRule`. Looks good now to me - can you confirm?

**Comment by dr0i** [comment] 2021-10-04 09:55
Commited apache configs. Closing.

**Closed as completed by dr0i** 2021-10-04 09:55 UTC
